### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by xingorg1** [xingorg1/xingorg1Note#3]
## 🤔结果 & 预期

Please describe what you expected to see.(请描述一下你希望看到什么)

## 🐥环境 & 设置

**Node.js & npm version**

```bash
```

**Comment by xingorg1** [comment]
/* 第一种： */
.quiz {}

.quiz-h {
  vertical-align: middle;
  padding: 0 10px;
}

.quiz-p {
  display: table-cell;
  padding-right: 10px;
}

/* 第2种： */
.quiz {
  align-items: center;
  justify-content: center;
}

.quiz-h {
  padding: 0 10px;
}

.quiz-p {
  padding-right: 10px;
}

/* 第3种： */
.quiz {
  white-space: nowrap;
  overflow: hidden;
}

.quiz-h {
  padding: 0 10px;
}

.quiz-p {
  white-space: normal;
  vertical-align: bottom;
  margin-right: 90px;
}

/* 第4种 */
.quiz {
  position: relative;
}

.quiz-h {
  left: 10px;
}

.quiz-p {
  padding-right: 10px;
  padding-left: 80px;
}

**Comment by xingorg1** [comment]
第一种：
```css
.quiz {}

.quiz-h {
  vertical-align: middle;
  padding: 0 10px;
}

.quiz-p {
  display: table-cell;
  padding-right: 10px;
}
```
第2种：
```css
.quiz {
  align-items: center;
  justify-content: center;
}

.quiz-h {
  padding: 0 10px;
}

.quiz-p {
  padding-right: 10px;
}

```
第3种：
```css
.quiz {
  white-space: nowrap;
  overflow: hidden;
}

.quiz-h {
  padding: 0 10px;
}

.quiz-p {
  white-space: normal;
  vertical-align: bottom;
  margin-right: 90px;
}
```
第4种：
```css
.quiz {
  position: relative;
}

.quiz-h {
  left: 10px;
}

.quiz-p {
  padding-right: 10px;
  padding-left: 80px;
}
```
